### ISSUE TITLE
incorrect license used

### ISSUE THREAD

**Issue by danmarsden** [hxtree/moodle-submission_backup#1]
If you are writing a Moodle block/plugin, it is a derivative of Moodle and therefore the GPL requires that all derivatives also be under the terms GPL.

If you have 3rd party libraries inside your plugin - you can include them with their associated licences, but the moodle components of your plugin need to be GPL sorry!

**Comment by hxtree** [comment]
Changed to GPL 11e6d72eeeec0a8795b6131a602cdc1af84a48cf
