### ISSUE TITLE
camel case

### ISSUE THREAD

**Issue by danmarsden** [hxtree/moodle-submission_backup#4]
Moodle uses sentance case - things like this:
$string['pluginname'] = 'My Submissions';
$string['submission_backup'] = 'Submission Backup';

should be more like:
$string['pluginname'] = 'My submissions';
$string['submission_backup'] = 'Submission backup';

**Comment by hxtree** [comment]
Fix with 9343ce83b0c25f0a1dcec677b007712142129b2b
